"""score_bigint

Revision ID: 5fde9011f622
Revises: f3a2b1c0d9e8
Create Date: 2026-04-07 22:10:28.401767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fde9011f622'
down_revision: Union[str, Sequence[str], None] = 'f3a2b1c0d9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_occurrences_event_id'), table_name='event_occurrences')
    op.alter_column('event_participations', 'score',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint(op.f('event_participations_event_id_fkey'), 'event_participations', type_='foreignkey')
    op.create_foreign_key(None, 'event_participations', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_participations', type_='foreignkey')
    op.create_foreign_key(op.f('event_participations_event_id_fkey'), 'event_participations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.alter_column('event_participations', 'score',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('ix_event_occurrences_event_id'), 'event_occurrences', ['event_id'], unique=False)
    # ### end Alembic commands ###
